import type { Metadata } from "next";
import { Zalando_Sans_Expanded, Nunito_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";

const ZalandoSansExpanded = Zalando_Sans_Expanded({
  variable: "--font-zalando-sans-expanded",
  subsets: ["latin"],
  fallback: ["system-ui", "Arial", "sans-serif"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ZalandoSansExpanded.variable} ${nunitoSans.variable} antialiased`}
      >
        <div className="max-w-480 w-[90%] mx-auto">
          <Navbar />
          {children}
        </div>
        
      </body>
    </html>
  );
}
